### ISSUE TITLE
Can't get all available metrics?

### ISSUE THREAD

**Issue by hiscal2015** [ofesseler/gluster_exporter#10]
Hi, 

From the instructions of README, seems this exporter has a lot of metrics to use, but why I can see only 9 items? See below picture:

![gluspro](https://cloud.githubusercontent.com/assets/15604715/24342151/90dd5c7a-12f1-11e7-9a7e-2d538604ad52.jpg)

**Comment by ofesseler** [comment]
to get the profiling metrics uyou have to enable them with the `-profile true` flag and also you have to enable profiling with the `gluster`-command.
```
gluster volume profile <volume-name> start
```

That's probably not that clear in README.md.

**Comment by hiscal2015** [comment]
@ofesseler Thanks for the clarification.
