### ISSUE TITLE
I am interested in continuing this project

### ISSUE THREAD

**Issue by stefanmonkey** [ofesseler/gluster_exporter#22]
Tks your code can running in production environment;
I just interesting in continuing this project. 

But I am a new gopher. How to connect you?

PS: I change your project code structure like mysql_exporter.

**Comment by ofesseler** [comment]
my email address is linked to my profile, so you can get in contact through this way for example.

I think it is necessary to refactor the code and give it a cleaner structure.
Recently @coder-hugo  has also shown interest in continuing this project. But the pull requests are still open and I'd recommend that you both get in touch...

**Comment by stefanmonkey** [comment]
I have made a pr #23.

**Comment by mjtrangoni** [comment]
Hi @stefanmonkey, @ofesseler, @coder-hugo,

What is the status here? I would like to use this exporter, and I can contribute fixing issues, making code reviews, and refactoring too.

**Comment by ofesseler** [comment]
If you have time and are ready to conrtibute and test some code, accept pull requests and build errors, you are very welcome.

**Comment by mjtrangoni** [comment]
@ofesseler Thank you! I will be contributing soon.

**Comment by mjtrangoni** [comment]
@ofesseler can we close this issue?
