### ISSUE TITLE
Export inode information

### ISSUE THREAD

**Issue by mjtrangoni** [ofesseler/gluster_exporter#27]
We should be exporting  `gluster_node_inode_count` and `gluster_node_inode_free` metrics as well as we do with the size metrics.

See,
```
# gluster volume status all detail
Status of volume: test-volume
------------------------------------------------------------------------------
Brick                : Brick glusterfs1:/data/brick1/gv0
TCP Port             : 49152
RDMA Port            : 0
Online               : Y
Pid                  : 1942
File System          : xfs
Device               : /dev/sdb1
Mount Options        : rw,seclabel,relatime,attr2,inode64,noquota
Inode Size           : 512
Disk Space Free      : 499.6GB
Total Disk Space     : 499.8GB
Inode Count          : 262143424
Free Inodes          : 262143110
```

@ofesseler any thoughts?

**Comment by ofesseler** [comment]
Good idea, since the idea of this exporter was to map the cluster metrics in Prometheus metrics format. 

Additionally inode information could be quite useful.

**Comment by ofesseler** [comment]
Good idea, since the idea of this exporter was to map the cluster metrics in Prometheus metrics format. 

Additionally inode information could be quite useful.
