### ISSUE TITLE
build failed 

### ISSUE THREAD

**Issue by ofesseler** [ofesseler/gluster_exporter#34]
gometallinter error 
see travis log: https://api.travis-ci.org/v3/job/408065174/log.txt

**Comment by mjtrangoni** [comment]
@ofesseler This is because of [gosec](https://github.com/securego/gosec), which seems to be added to gometalinter defaults. We should disable it adding `--disable=gosec` in [Makefile](Makefile).

**Comment by ofesseler** [comment]
closed with #35
